### PR TITLE
Log PeerClosedStreamExceptions as warnings instead of errors

### PR DESCRIPTION
**Pull request by ladinu**
The `GrpcExceptionHandler` logs `PeerClosedStreamException` as an error. This is causing log spam in cloud environments where clients abruptly terminate. The exception should be logged as a warning instead.

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm, reasoning behind this change seems valid. @pjfanning , @He-Pin , @raboof , @Roiocam wdyt?

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
Merged - thanks @ladinu

**Comment by ladinu** [comment]
Thank you!

**Pull request merged**
